DROP TABLE IF EXISTS countries CASCADE;

CREATE TABLE countries (
    id SERIAL PRIMARY KEY,
    country TEXT,
    countrydisplayname TEXT,
    countryimg VARCHAR,
    countrydescriptionlong VARCHAR,
    countrydescriptionshort VARCHAR
);

INSERT INTO countries (country, countrydisplayname, countryimg, countrydescriptionlong, countrydescriptionshort) VALUES ('morocco','Morocco','https://surfforecast.s3.amazonaws.com/morocco1.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit. Lobortis mattis aliquam faucibus purus in massa tempor nec. Lectus quam id leo in vitae turpis massa sed. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Ut tellus elementum sagittis vitae et leo duis ut. Vitae congue eu consequat ac felis donec et. Cursus eget nunc scelerisque viverra mauris in aliquam. Nibh tellus molestie nunc non blandit. Ullamcorper sit amet risus nullam eget felis eget nunc. In aliquam sem fringilla ut morbi tincidunt augue interdum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit.'),
('portugal','Portugal','https://surfforecast.s3.amazonaws.com/zachary-pearson-co0j6jpEpek-unsplash.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit. Lobortis mattis aliquam faucibus purus in massa tempor nec. Lectus quam id leo in vitae turpis massa sed. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Ut tellus elementum sagittis vitae et leo duis ut. Vitae congue eu consequat ac felis donec et. Cursus eget nunc scelerisque viverra mauris in aliquam. Nibh tellus molestie nunc non blandit. Ullamcorper sit amet risus nullam eget felis eget nunc. In aliquam sem fringilla ut morbi tincidunt augue interdum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit.'),
('spain','Spain','https://surfforecast.s3.amazonaws.com/hector-arguello-canals-kJVCqFxcdVw-unsplash.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit. Lobortis mattis aliquam faucibus purus in massa tempor nec. Lectus quam id leo in vitae turpis massa sed. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Ut tellus elementum sagittis vitae et leo duis ut. Vitae congue eu consequat ac felis donec et. Cursus eget nunc scelerisque viverra mauris in aliquam. Nibh tellus molestie nunc non blandit. Ullamcorper sit amet risus nullam eget felis eget nunc. In aliquam sem fringilla ut morbi tincidunt augue interdum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit.'),
('france','France','https://surfforecast.s3.amazonaws.com/eric-terrade-U6g5vUaJBGE-unsplash.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit. Lobortis mattis aliquam faucibus purus in massa tempor nec. Lectus quam id leo in vitae turpis massa sed. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Ut tellus elementum sagittis vitae et leo duis ut. Vitae congue eu consequat ac felis donec et. Cursus eget nunc scelerisque viverra mauris in aliquam. Nibh tellus molestie nunc non blandit. Ullamcorper sit amet risus nullam eget felis eget nunc. In aliquam sem fringilla ut morbi tincidunt augue interdum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit.'),
('thenetherlands','The Netherlands','https://surfforecast.s3.amazonaws.com/lucie-van-beek-lBrCqPxCCnQ-unsplash.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit. Lobortis mattis aliquam faucibus purus in massa tempor nec. Lectus quam id leo in vitae turpis massa sed. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Ut tellus elementum sagittis vitae et leo duis ut. Vitae congue eu consequat ac felis donec et. Cursus eget nunc scelerisque viverra mauris in aliquam. Nibh tellus molestie nunc non blandit. Ullamcorper sit amet risus nullam eget felis eget nunc. In aliquam sem fringilla ut morbi tincidunt augue interdum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit.'),
('england','England','https://surfforecast.s3.amazonaws.com/nathan-hill-haimes-BuhcNx3Ea04-unsplash+(1).jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit. Lobortis mattis aliquam faucibus purus in massa tempor nec. Lectus quam id leo in vitae turpis massa sed. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Ut tellus elementum sagittis vitae et leo duis ut. Vitae congue eu consequat ac felis donec et. Cursus eget nunc scelerisque viverra mauris in aliquam. Nibh tellus molestie nunc non blandit. Ullamcorper sit amet risus nullam eget felis eget nunc. In aliquam sem fringilla ut morbi tincidunt augue interdum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In massa tempor nec feugiat nisl pretium fusce id velit.');
    